### ISSUE TITLE
Crash when user update

### ISSUE THREAD

**Issue by MaximeDelhorme** [jonasbark/flutter_in_app_update#108]
Hi,

All my Android users are experiencing a crash on update.
Here is the crash log.

Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

Caused by android.content.IntentSender$SendIntentException:
       at android.app.Activity.startIntentSenderForResultInner(Activity.java:4855)
       at android.app.Activity.startIntentSenderForResult(Activity.java:4824)
       at com.google.android.play.core.appupdate.zze.startIntentSenderForResult(com.google.android.play:core@@1.10.3:1)
       at com.google.android.play.core.appupdate.zzf.startUpdateFlowForResult(com.google.android.play:core@@1.10.3:9)
       at com.google.android.play.core.appupdate.zzf.startUpdateFlowForResult(com.google.android.play:core@@1.10.3:2)
       at de.ffuf.in_app_update.InAppUpdatePlugin.onActivityResumed$lambda-0(InAppUpdatePlugin.kt:150)
       at de.ffuf.in_app_update.InAppUpdatePlugin.lambda$3XJZpbWv7mcDfk_mt2k7JkkWXKo(InAppUpdatePlugin.kt)
       at de.ffuf.in_app_update.-$$Lambda$InAppUpdatePlugin$3XJZpbWv7mcDfk_mt2k7JkkWXKo.onSuccess(lambda:6)
       at com.google.android.play.core.tasks.zze.run(com.google.android.play:core@@1.10.3:1)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

I am using version: in_app_update: ^4.0.1

Have you seen this error before? Is it solved in the versions after that?

**Comment by MaximeDelhorme** [comment]
Edited initial post with full crash log. Let me know if you need more info.

**Comment by jonasbark** [comment]
Thanks

You mentioned that it happens during the update. Can you specify? Does it happen right when it performs the actual update? If so, then this crash may actually be expected

**Comment by MaximeDelhorme** [comment]
So the user is prompted is the update message in my app, then clicks on update.
Some kind of google play screen opens and the update starts with a loading bar showing the update progress.

At one point in the update progress the process crash and the update window and the app are both suddenly closed.

**Comment by jonasbark** [comment]
in any case there is nothing that the plugin can do here

**Comment by MaximeDelhorme** [comment]
The app seems correctly installed, but the fact that I get a crash log seems to indicate that this is indeed an unwanted termination of the app. Thanks for the help anyhow.
