### ISSUE TITLE
The application crashes when the checkForUpdate() method is called

### ISSUE THREAD

**Issue by coolswood** [jonasbark/flutter_in_app_update#99]
After upgrading to version 4.1.0, I get the following error when calling the checkForUpdate() method

```
I/PlayCore(23269): UID: [10768]  PID: [23269] AppUpdateService : requestUpdateInfo(com.cbt.mindhealthy)
I/PlayCore(23269): UID: [10768]  PID: [23269] AppUpdateService : Initiate binding to the service.
I/PlayCore(23269): UID: [10768]  PID: [23269] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore(23269): UID: [10768]  PID: [23269] AppUpdateService : linkToDeath
I/PlayCore(23269): UID: [10768]  PID: [23269] OnRequestInstallCallback : onRequestInfo
I/PlayCore(23269): UID: [10768]  PID: [23269] AppUpdateService : Unbind from service.
D/AndroidRuntime(23269): Shutting down VM
E/AndroidRuntime(23269): FATAL EXCEPTION: main
E/AndroidRuntime(23269): Process: com.cbt.mindhealthy, PID: 23269
E/AndroidRuntime(23269): java.lang.IllegalArgumentException: Unsupported value: '[]' of type 'class java.util.HashSet'
E/AndroidRuntime(23269): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/AndroidRuntime(23269): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime(23269): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:61)
E/AndroidRuntime(23269): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
E/AndroidRuntime(23269): 	at de.ffuf.in_app_update.InAppUpdatePlugin$checkForUpdate$2.invoke(InAppUpdatePlugin.kt:237)
E/AndroidRuntime(23269): 	at de.ffuf.in_app_update.InAppUpdatePlugin$checkForUpdate$2.invoke(InAppUpdatePlugin.kt:235)
E/AndroidRuntime(23269): 	at de.ffuf.in_app_update.InAppUpdatePlugin.checkForUpdate$lambda$5(InAppUpdatePlugin.kt:235)
E/AndroidRuntime(23269): 	at de.ffuf.in_app_update.InAppUpdatePlugin.$r8$lambda$cf6QoRdJ6nEKxgYvRIY6ZjFyhvo(Unknown Source:0)
E/AndroidRuntime(23269): 	at de.ffuf.in_app_update.InAppUpdatePlugin$$ExternalSyntheticLambda1.onSuccess(Unknown Source:2)
E/AndroidRuntime(23269): 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/AndroidRuntime(23269): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(23269): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23269): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(23269): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(23269): 	at android.app.ActivityThread.main(ActivityThread.java:7884)
E/AndroidRuntime(23269): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23269): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(23269): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process (23269): Sending signal. PID: 23269 SIG: 9
```

**Comment by jonasbark** [comment]
thanks for reporting
